openapi: 3.0.0
info:
  description: Backend for Makeup-mirror Android App
  version: "1.0.0"
  title: Makeup-mirror
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/portal.tech/makeup-mirror/1.0.0
  - url: 'https://petstore.swagger.io/v2'
tags:
  - name: brand
    description: Everything about Brands, used for Makeup-mirror
    externalDocs:
      description: Find out more about our App
      url: 'http://makeup-mirror.io'
paths:
  '/rest-api/v1/brand/search':
    get:
      tags:
        - brand
      summary: Search All Brands
      description: It is reserved for query/filter to be supplied lately. But just now there are no params and result is all brands
      operationId: searchBrands
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Brand'
        '400':
          description: Invalid status value
  '/rest-api/v1/brand/id/{id_brand}':
    get:
      tags:
        - brand
      summary: Find brand by ID
      description: Returns a single brand
      operationId: getBrandById
      parameters:
        - name: id_brand
          in: path
          description: ID of brand to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Brand'
        '400':
          description: Invalid ID supplied. ID value should be int
        '404':
          description: Brand not found
    delete:
      tags:
        - brand
      summary: Deletes a brand
      operationId: deleteBrand
      parameters:
        - name: id_brand
          in: path
          description: Brand id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Invalid ID supplied. ID value should be int
        '404':
          description: Brand not found
  '/rest-api/v1/brand/set':
    post:
      tags:
        - brand
      summary: Add/Update a brand in the store with data provided
      operationId: putBrand
      requestBody:
        description: Brand by form-fields
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Brand'
      responses:
        '405':
          description: Invalid input
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
components:
  schemas:
    Brand:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
